docker-compose build azurite
docker-compose build azurite-setup
docker-compose build sql-database
docker-compose build database-setup
docker-compose build base-image
docker-compose build create-ps-episode-data
docker-compose build create-ps-profile-data
docker-compose build get-ps-profile-data
docker-compose build get-ps-episode-data
docker-compose build create-ps-episode
docker-compose build create-ps-profile
docker-compose build get-ps-profile
docker-compose build get-ps-episode
docker-compose build get-demographics-data
docker-compose build create-episode
docker-compose build get-episode
docker-compose build retrieve-episode-ref-data
docker-compose build update-episode
docker-compose build receive-data
docker-compose build create-update-episode
docker-compose build get-episode-mgmt
docker-compose build get-episode-ref-data
docker-compose build retrieve-mesh-file
docker-compose build get-participant
docker-compose build update-participant
docker-compose build get-organisation-data
docker-compose build get-screening-data

