name: service-insights

# Define network
networks:
  app-network:
    driver: host

# Define services
services:
  # External Dependencies
  azurite:
    container_name: azurite
    network_mode: host
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --silent
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azurite-setup:
    container_name: azurite-setup
    network_mode: host
    build:
      context: ./scripts
      dockerfile: ./azurite/Dockerfile
    depends_on:
      - azurite
    environment:
      - AZURITE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}
      - AZURITE_CONTAINER_NAME=${AZURITE_CONTAINER_NAME}

  sql-database:
    container_name: sql-database
    network_mode: host
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "grep -q 'SQL Server is now ready for client connections' /var/opt/mssql/log/errorlog || exit 1",
        ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s

  database-setup:
    container_name: database-setup
    network_mode: host
    build:
      context: ./scripts/
      dockerfile: ./database/Dockerfile
    depends_on:
      sql-database:
        condition: service_healthy
    environment:
      - PASSWORD=${PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_CONNECTION=${DB_CONNECTION}

  # BI Analytics Data Service
  create-participant-screening-episode:
    container_name: create-participant-screening-episode
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./BIAnalyticsDataService/CreateParticipantScreeningEpisode/Dockerfile
    ports:
      - "6010:6010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6010
      - ServiceInsightsDbConnectionString=Server=${DB_CONNECTION},1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  create-participant-screening-profile:
    container_name: create-participant-screening-profile
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./BIAnalyticsDataService/CreateParticipantScreeningProfile/Dockerfile
    ports:
      - "6011:6011"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6011
      - ServiceInsightsDbConnectionString=Server=${DB_CONNECTION},1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  # BI Analytics Service
  create-data-assets:
    container_name: create-data-assets
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./BIAnalyticsService/CreateDataAssets/Dockerfile
    ports:
      - "6009:6009"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6009
      - GetEpisodeUrl=http://127.0.0.1:6060/api/GetEpisode
      - GetParticipantUrl=http://127.0.0.1:6061/api/GetParticipant
      - CreateParticipantScreeningEpisodeUrl=http://127.0.0.1:6010/api/CreateParticipantScreeningEpisode
      - CreateParticipantScreeningProfileUrl=http://127.0.0.1:6011/api/CreateParticipantScreeningProfile

  # Episode Data Service
  create-episode:
    container_name: create-episode
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeDataService/CreateEpisode/Dockerfile
    ports:
      - "6007:6007"
    environment:
      - ASPNETCORE_URLS=http://*:6007
      - ServiceInsightsDbConnectionString=Server=127.0.0.1,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  get-episode:
    container_name: get-episode
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeDataService/GetEpisode/Dockerfile
    ports:
      - "6070:6070"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6070
      - ServiceInsightsDbConnectionString=Server=127.0.0.1,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  update-episode:
    container_name: update-episode
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeDataService/UpdateEpisode/Dockerfile
    ports:
      - "7777:7777"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:7777
      - ServiceInsightsDbConnectionString=Server=127.0.0.1,1433;Database=${DB_NAME};User Id=SA;Password=${PASSWORD};TrustServerCertificate=True

  # Episode Integration Service
  receive-data:
    container_name: receive-data
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeIntegrationService/ReceiveData/Dockerfile
    depends_on:
      - azurite
    ports:
      - "7071:7071"
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:7071
      - ProcessDataURL=http://127.0.0.1:7072/api/ProcessData

  process-data:
    container_name: process-data
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeIntegrationService/ProcessData/Dockerfile
    ports:
      - "7072:7072"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:7072
      - EpisodeManagementUrl=http://127.0.0.1:6006/api/CreateUpdateEpisode
      - ParticipantManagementUrl=http://127.0.0.1:7074/api/UpdateParticipant

  # Episode Management Service
  create-update-episode:
    container_name: create-update-episode
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeManagementService/CreateUpdateEpisode/Dockerfile
    ports:
      - "6006:6006"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6006
      - CreateEpisodeUrl=http://127.0.0.1:6007/api/CreateEpisode
      - GetEpisodeUrl=http://127.0.0.1:6060/api/GetEpisode
      - UpdateEpisodeUrl=http://127.0.0.1:7777/api/UpdateEpisode

  get-episode-mgmt:
    container_name: get-episode-mgmt
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./EpisodeManagementService/GetEpisode/Dockerfile
    ports:
      - "6060:6060"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6060
      - GetEpisodeUrl=http://127.0.0.1:6070/api/GetEpisode

      # Mesh Mailbox Management Service
  retrieve-mesh-file:
    container_name: retrieve-mesh-file
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./MeshIntegrationService/RetrieveMeshFile/Dockerfile
    depends_on:
      - azurite
    ports:
      - "6777:6777"
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ASPNETCORE_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6777
      - MeshApiBaseUrl=${MESHAPIBASEURL}
      - BSSMailBox=${BSSMAILBOX}
      - BSSContainerName=${AZURITE_CONTAINER_NAME}
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}

  # Participant Management Service
  get-participant:
    container_name: get-participant
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./ParticipantManagementService/GetParticipant/Dockerfile
    ports:
      - "6061:6061"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:6061

  update-participant:
    container_name: update-participant
    network_mode: host
    build:
      context: ./src/
      dockerfile: ./ParticipantManagementService/UpdateParticipant/Dockerfile
    ports:
      - "7074:7074"
    environment:
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - ASPNETCORE_URLS=http://*:7074
