USE ServiceInsightsDB;
GO

IF NOT EXISTS
(
    SELECT *
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'EPISODE'
)
BEGIN
    CREATE TABLE EPISODE
    (
        EPISODE_ID BIGINT NOT NULL,
        CONSTRAINT PK_EPISODE
            PRIMARY KEY (EPISODE_ID)
    );
END
