USE ServiceInsightsDB;
GO

-- Remove foreign key constraints from EPISODE
IF OBJECT_ID('dbo.EPISODE', 'U') IS NOT NULL
BEGIN
    ALTER TABLE dbo.EPISODE
        DROP CONSTRAINT IF EXISTS FK_EPISODE_END_CODE_LKP;
    ALTER TABLE dbo.EPISODE
        DROP CONSTRAINT IF EXISTS FK_EPISODE_EPISODE_TYPE_LKP;
    ALTER TABLE dbo.EPISODE
        DROP CONSTRAINT IF EXISTS FK_EPISODE_FINAL_ACTION_CODE_LKP;
    ALTER TABLE dbo.EPISODE
        DROP CONSTRAINT IF EXISTS FK_EPISODE_REASON_CLOSED_CODE_LKP;
END

-- Drop each table if it exists, with EPISODE last
IF OBJECT_ID('dbo.PARTICIPANT_SCREENING_EPISODE', 'U') IS NOT NULL
    DROP TABLE dbo.PARTICIPANT_SCREENING_EPISODE;
GO

IF OBJECT_ID('dbo.PARTICIPANT_SCREENING_PROFILE', 'U') IS NOT NULL
    DROP TABLE dbo.PARTICIPANT_SCREENING_PROFILE;
GO

IF OBJECT_ID('dbo.END_CODE_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.END_CODE_LKP;
GO

IF OBJECT_ID('dbo.EPISODE_TYPE_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.EPISODE_TYPE_LKP;
GO

IF OBJECT_ID('dbo.FINAL_ACTION_CODE_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.FINAL_ACTION_CODE_LKP;
GO

IF OBJECT_ID('dbo.REASON_CLOSED_CODE_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.REASON_CLOSED_CODE_LKP;
GO

IF OBJECT_ID('dbo.EPISODE', 'U') IS NOT NULL
    DROP TABLE dbo.EPISODE;
GO

IF OBJECT_ID('dbo.ORGANISATION_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.ORGANISATION_LKP;
GO

IF OBJECT_ID('dbo.SCREENING_LKP', 'U') IS NOT NULL
    DROP TABLE dbo.SCREENING_LKP;
GO
